#%RAML 1.0
title: CRM System API
baseUri: http://localhost:8080/api/v1/crm
description: Customer Relationship Management System
mediaType: 
  - application/xml
version: 1.0.0
protocols:
  - HTTPS

types:
  ErrorPayload: !include types/errors/error-payload-dataType.raml
  Customer: !include types/responses/get-customer-response-datatype.raml

/customers:
  /{customerId}:
    uriParameters:
      customerId:
        type: string
        required: true
        pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    get:
      description: Retrieve customer information
      displayName: GetCustomerById
      responses:
        200:
          description: Returns Customer detail
          body:
            application/xml:
              type: Customer
              example: !include examples/responses/get-customer-response-payload.xml
        404:
          description: Customer not found
          body: 
            application/xml:
              type: ErrorPayload
              example: !include examples/errors/customer-not-found-error-payload.xml
        500:
          description: Internal Server error
          body:
            application/xml:
              type: ErrorPayload
              example: !include examples/errors/internal-server-error-payload.xml
