#%RAML 1.0 Trait

headers:
  x-correlation-id:
    description:   Provides the standard correlation identifier used to tracen a business operation across APIs.
    type: string
    required: true
    example: "7e4c9e11-3f12-4a89-9a81-28d1c7f0b5d2"