#%RAML 1.0 DataType

type: object
properties:

  orderId:
    type: string
    required: true
    pattern: "^ORD-[0-9]{1,6}$"

  status:
    type: string
    required: true
    enum:
      - CREATED
      - SHIPPED
      - CANCELLED

  customerId:
    type: string
    required: true

  totalAmount:
    type: number
    required: true

  currency:
    type: string
    required: true
    enum: [EUR, USD]

  items:
    type: array
    required: true
    minItems: 1
    items:
      type: object
      properties:

        productId:
          type: string
          required: true
          pattern: "^PROD-[0-9]{1,6}$"

        name:
          type: string
          required: true

        quantity:
          type: integer
          required: true
          minimum: 1

        unitPrice:
          type: number
          required: true

        totalPrice:
          type: number
          required: true

  createdAt:
    type: datetime
    required: true

  updatedAt:
    type: datetime
    required: true
