db:
  url: "jdbc:postgresql://ep-flat-mud-b4uj4uj1-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  driver_class_name: "org.postgresql.Driver"
  username: "neondb_owner"
  password: "npg_1F5ThLksrbVo"